/smb/stage_interface_node:
  ros__parameters:
    world_frame: "world"
    PlanningParams:
      planner_mode:     "kSim" #"kReal"
      type:             kBasicExploration #kAdaptiveExploration, kBasicExploration
      rr_mode:          kGraph
      exp_sensor_list:  ["OS064"]
      global_frame_id: "world"
      pose_graph_update_dist: 0.75 # initialization motion forward m
      dt:               0.1 # dt for traj 
      distance_to_new_path: 0.5
      distance_to_new_wp: 0.5
      clustering_radius: 0.5
      edge_length_min:  -0.1
      edge_length_max:  3.0
      local_space: 20.0 
      path_interpolation_distance: 1.5
      edge_overshoot:   0.0 #m
      num_connections_max: 10.0 # maximum edges a vertex can have
      num_vertices_max: 1000.0
      num_edges_max:    9000.0
      num_loops_cutoff: 2000.0
      num_loops_max:    20000.0
      nearest_range:    2.5
      nearest_range_min: 0.1 # >= edge_length_min
      nearest_range_max: 3.0 # <= edge_length_max
      exploration_time_budget: 3600.0 # seconds
  
      ## manual mode params 
      graph_density_scalar: 2.0 # num vertices,edges and loops cutoff is scaled by this factor to make denser or sparse graph in kManualMode. 


      use_current_state: true
      augment_free_voxels_time: 1.0
      free_frustum_before_planning: false
      use_ray_model_for_volumetric_gain: true
      path_length_penalty: 0.07
      path_direction_penalty: 0.3
      hanging_vertex_penalty: 5.0
      exp_gain_voxel_size: 0.8
      occupied_voxel_gain: 0.0
      free_voxel_gain:  0.0 #prefer directions towards more free voxels in case of the dead-end
      unknown_voxel_gain: 60.0
      nonuniform_ray_cast: true
      ray_cast_step_size_multiplier: 1.0
      freespace_cloud_enable: false
      leafs_only_for_volumetric_gain: false
      cluster_vertices_for_gain: true
  
      max_ground_height: 0.7 # All points will be projected to this height from ground
      robot_height: 0.6  # Height of robot's base frame from ground
      max_inclination: 0.4363 #rad(25.0*pi/180)
      interpolate_projection_distance: false
  
      yaw_tangent_correction: true
      traverse_length_max: 6.0
      traverse_time_max: 40.0
      path_safety_enhance_enable: true
  
      auto_global_planner_enable: true
      relaxed_corridor_multiplier: 1.5
      homing_backward: false
      auto_homing_enable: true
      # global_frame_id: "world"
      global_path_inclination_check: true
      go_home_if_fully_explored: true
      geofence_checking_enable: true

    AdaptiveObbParams:
      type: kPca
      local_pointcloud_range: 50.0
      bounding_box_size_max: 35

    SensorParams:
      # sensor_list: ["OS064", "fake_cam"]
      sensor_list: ["OS064"]
      OS064:
        type: kLidar
        max_range: 8.0
        center_offset: [0.0, 0.0, 0.0]
        rotations: [0.0, 0.0, 0.0]
        fov: [6.28319, 0.523599]  # Numerical values for rad(2*pi) and rad(pi/6)
        resolution: [0.1221, 0.1221] # Numerical values for rad(7*pi/180)
        frontier_percentage_threshold: 0.1
      # fake_cam:
      #   type: kCamera
      #   max_range: 5.0
      #   center_offset: [0.0, 0.0, 0.0]
      #   rotations: [0.0, 0.0, 0.0]
      #   fov: [6.28319, 0.523599]  # Numerical values for rad(2*pi) and rad(pi/6)
      #   resolution: [0.1221, 0.1221] # Numerical values for rad(7*pi/180)
      #   frontier_percentage_threshold: 0.1

    RobotParams:
      type: kGroundRobot
      size: [0.6, 0.6, 0.4] # Actual size of the robot in meters [x, y, z]
      size_extension_min: [0.2, 0.2, 0.2] # minimum extension outside of robot size allowed to operate
      size_extension: [0.4, 0.4, 0.4] # maximum extension outside of the robot size
      center_offset: [0.0, 0.0, 0.0]
      relax_ratio: 0.5 # Used to define an intermediate size between size_extension_min and size_extension for planning
      bound_mode: kExtendedBound
      safety_extension: [1.5, 1.5, 1.0] # Safety extension outside the bounding box of a path segment used to improve it by pushing it away from obstacles

    GraphExpansionParams:
      Global:
        type: kCuboid
        min_val: [-3000.0, -3000.0, -300.0]
        max_val: [3000.0, 3000.0, 300.0]
      Local:
        type: kCuboid
        min_val: [-2.0, -2.0, -2.0]
        max_val: [2.0, 2.0, 2.0]
        min_extension: [-2.0, -2.0, -2.0]
        max_extension: [2.0, 2.0, 2.0]
      LocalSearch:
        type: kCuboid
        min_val: [-50.0, -50.0, -1.0]
        max_val: [50.0, 50.0, 1.0]
      # Adaptive OBB:
      LocalAdaptiveExp:
        type: kCuboid
        min_val: [-10.0, -10.0, -0.75]
        max_val: [10.0, 10.0, 0.75]

    BoundedSpaceParams:
      Global:
        type: kCuboid
        min_val: [-3000.0, -3000.0, -300.0]
        max_val: [3000.0, 3000.0, 300.0]
      Local:
        type: kCuboid
        min_val: [-15.0, -15.0, -15.0]
        max_val: [15.0, 15.0, 15.0]
        min_extension: [-15.0, -15.0, -15.0]
        max_extension: [15.0, 15.0, 15.0]
      LocalSearch:
        type: kCuboid
        min_val: [-50.0, -50.0, -10.0]
        max_val: [50.0, 50.0, 10.0]
      # Adaptive OBB:
      LocalAdaptiveExp:
        type: kCuboid
        min_val: [-10.0, -10.0, -0.75]
        max_val: [10.0, 10.0, 0.75]

    RandomSamplerParams:
      SamplerForExploration:
        X:
          pdf_type: kUniform
          sample_mode: kLocal
        Y:
          pdf_type: kUniform
          sample_mode: kLocal
        Z:
          pdf_type: kUniform
          sample_mode: kLocal
        Heading:
          pdf_type: kUniform
          sample_mode: kManual
          min_val: "rad(-pi)"
          max_val: "rad(pi)"
